name: Build and publish the Docker image

on:
  push:
    tags: ["release"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nonk123/vga9x16

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  deploy:
    name: Deploy the public instance
    if: github.ref_name == 'release'
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        with:
          host: vga9x16.ru
          username: root
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE
          script: |
            docker pull $IMAGE
            docker container rm --force vga9x16 || true
            docker run -d --name vga9x16 --network caddy --restart always $IMAGE
